sudo: required

env:
  global:
    - "OBS_API_URL=https://api.opensuse.org:443/trigger/runservice"

services:
    - docker

before_install:
    - make docker-build

script:
    - make docker-test

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - curl -s -X POST -H 'Authorization: Token $OBS_TOKEN' $OBS_API_URL
